In [1]:
import torch
a = torch.randn(0,2)
print(a.type())
isinstance(a, torch.FloatTensor)
b=torch.tensor(1.)
print(b)
c = torch.tensor([1.3,12])
print(c)
print(c.shape)
print(c.dim())
print(c.size())

d=torch.FloatTensor(2,3)
print(d)
print(d.shape)
print(d.dim())

e=torch.ones(3,4,2)
print(e)
print(e.dim())
print(e.shape)
print(e.size(0))

ModuleNotFoundError: No module named 'torch'

In [32]:
f = torch.rand(1,2,3)
print(f)

tensor([[[0.3484, 0.9383, 0.1361],
         [0.6953, 0.8978, 0.5822]]])


In [35]:
print(f.dim)
print(f.size())
print(f.shape)
print(f.numel())

<built-in method dim of Tensor object at 0x7f108aec1410>
torch.Size([1, 2, 3])
torch.Size([1, 2, 3])
6


In [43]:
import numpy as np
g=np.array([2,2.3])
h=torch.from_numpy(g)
print(h)
g=np.ones([2,3])
h = torch.from_numpy(g)
print(h)
g=torch.tensor([1.1,2.])
print(g)
g=torch.FloatTensor([1.1, 2.0])
print(g)
g=torch.tensor([[1,2],[3,4]])
print(g)

tensor([2.0000, 2.3000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([1.1000, 2.0000])
tensor([1.1000, 2.0000])
tensor([[1, 2],
        [3, 4]])


In [50]:
g=torch.empty(2,3)
print(g)
g=torch.Tensor(2,3)
print(g)
g=torch.FloatTensor(2,3)
print(g)
g=torch.IntTensor(2,3)
print(g)


tensor([[ 1.8847e+08,  4.5587e-41, -2.6489e-15],
        [ 3.0646e-41,  4.4842e-44,  0.0000e+00]])
tensor([[ 1.8847e+08,  4.5587e-41, -2.6716e-15],
        [ 3.0646e-41,  0.0000e+00,  0.0000e+00]])
tensor([[ 1.8847e+08,  4.5587e-41, -2.6547e-15],
        [ 3.0646e-41, -2.2241e-32,  4.5581e-41]])
tensor([[ 1295236192,       32532, -1490389840],
        [      21870, -1964574608,       32528]], dtype=torch.int32)


In [57]:
g=torch.rand(3,3)
print(g)
g=torch.randint(3,10,[3,3])
print(g)
g=torch.randn(3,3)
print(g)

tensor([[0.9683, 0.0624, 0.5229],
        [0.6256, 0.3751, 0.7619],
        [0.7913, 0.8144, 0.5907]])
tensor([[4, 6, 3],
        [9, 5, 5],
        [3, 8, 9]])
tensor([[-0.3112,  1.7755,  0.0406],
        [ 0.1649,  0.4827, -0.5854],
        [ 2.6178, -0.5622, -0.6759]])


In [69]:
g=torch.normal(mean=torch.full([10],0.), std=torch.arange(1,0,-0.1))
print(g)

tensor([ 0.2508,  0.4849, -0.3918,  0.7020, -0.0458,  0.2327, -0.2432,  0.0793,
         0.0089,  0.0792])


In [71]:
g=torch.linspace(0,10, steps=4)
print(g)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [72]:
g=torch.logspace(0, -1, steps=4)
print(g)

tensor([1.0000, 0.4642, 0.2154, 0.1000])


In [73]:
g=torch.ones(2,3)
print(g)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [74]:
g=torch.zeros(2,3)
print(g)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [77]:
g=torch.eye(2,3)
print(g)
g=torch.eye(3)
print(g)
g=torch.ones_like(g)
print(g)

tensor([[1., 0., 0.],
        [0., 1., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [82]:
g=torch.randperm(10)
g
print(g)
g

tensor([4, 7, 9, 3, 8, 5, 0, 6, 2, 1])


tensor([4, 7, 9, 3, 8, 5, 0, 6, 2, 1])