In [18]:
import torch

a = torch.tensor([1,2,3])
b = torch.tensor([2,3,4])

# element-wise   c = [a1*b1, ...., ai*bi, ...., an*bn]
c = torch.mul(a,b)
c_1 = torch.multiply(a,b)
c_2 = a*b
print(c, c_1, c_2)

# d = ∑ai*bi,  torch.dot = torch.sum(torch.mul(a,b))
d = torch.dot(a,b)
print(d)

# matrix multiply , n*m x m*n = n*n
e = torch.matmul(a,b)
a_1 = torch.tensor([[1,2,3],[2,3,4]])
b_1 = torch.tensor([[1,2],[2,3], [5,6]])
e_1 = torch.mm(a_1, b_1)
e_2 = torch.matmul(a_1, b_1)
print( e, e_1, e_2)


tensor([ 2,  6, 12]) tensor([ 2,  6, 12]) tensor([ 2,  6, 12])
tensor(20)
tensor(20) tensor([[20, 26],
        [28, 37]]) tensor([[20, 26],
        [28, 37]])


In [29]:
import torch

# view()相当于reshape、resize，重新调整Tensor的形状
a1 = torch.arange(0,16)
print(a1) # tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

a2 = a1.view(8, 2) # 将a1的维度改为8*2
a3 = a1.view(2, 8) # 将a1的维度改为2*8
a4 = a1.view(4, 4) # 将a1的维度改为4*4

a5 = a1.view(2,2,1,4)
# 更多的维度也没有问题，只要保证维度改变前后的元素个数相同就行,即 2*2*1*4=16。

print(a2)
print(a3)
print(a4)
print(a5)

#特殊用法：参数-1 (自动调整size)
a2 = a1.view(-1, 16)
a3 = a1.view(-1, 8)
a4 = a1.view(-1, 4)
a5 = a1.view(-1, 2)
a6 = a1.view(4*4, -1)
a7 = a1.view(1*4, -1)
a8 = a1.view(2*4, -1)

print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print(a8)



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[[[ 0,  1,  2,  3]],

         [[ 4,  5,  6,  7]]],


        [[[ 8,  9, 10, 11]],

         [[12, 13, 14, 15]]]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
   

In [30]:
a1 = torch.arange(0,16)
# a.reshape = a.view() + a.contiguous().view()。
print(a1.reshape(-1, 16))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])


In [25]:
import torch

#transpose 转置
a_1 = torch.tensor([[1,2,3],[2,3,4]])
b_1 = torch.tensor([[1,2],[2,3], [5,6]])

a_2 = a_1.transpose(0,1)
print(a_1.shape, a_2.shape)

b_2 = b_1.transpose(0,1)
print(b_1.shape, b_2.shape)


torch.Size([2, 3]) torch.Size([3, 2])
torch.Size([3, 2]) torch.Size([2, 3])


In [28]:
import torch
a_1 = torch.tensor([[1,2,3],[2,3,4]])
a_2 = a_1.repeat(1, 2, 1)
print(a_1.shape, a_2.shape)


torch.Size([2, 3]) torch.Size([1, 4, 3])
